### ISSUE TITLE
How do you set the database name?

### ISSUE THREAD

**Issue by nickperkinslondon** [nrw/spine-adapter#6]
The example code does not show how to actually save a document.  Very frustrating...will have to go searching...

**Comment by nrw** [comment]
`spine-adapter` will use whatever database your [Kanso](http://kan.so) app is running from. Check out the example `spine-adapter` app here: https://github.com/nrw/kanso-spine-todos. That should give you a clear idea of how to use it. For more on how to use [Spine](http://spinejs.com), check out the [Spine docs](http://spinejs.com/docs/index). For more on how to use Kanso, check out the [Kanso docs](http://kan.so/docs).

**Comment by nickperkinslondon** [comment]
but it's not POST-ing to the right URL!....here is my code:

```
$ = require 'jquery'
Spine = require 'spine/core'
require 'spine-adapter/couch-ajax'

class Quote extends Spine.Model
    @configure "Quote","name"
    @extend Spine.Model.CouchAjax

class App extends Spine.Controller
    constructor:->
        super
        @log "Spine App Initializing..."

do_something = =>

    q = new Quote
        name:'Nick Spine'

    q.bind 'save', (a,b,c)->
        debugger

    q.bind 'error', (a,b,c)->
        debugger

    q.save()
```

---

The database is at:
http;//localhost:5984/field-agent

The page is served from a "_show function at:
http://localhost:5984/field-agent/_design/field-agent/_show/new_quote/_design/field-agent

When I save() it sends POST to 
http://localhost:5984/spine-adapter/quote

The response is:
{"error":"not_found","reason":"no_db_file"}

The "save" event fires,
The "error" event does not fire.

Why is the POST not sent to the right URL?
Why doesn't the error event fire?

**Comment by nrw** [comment]
If you link me to a repository with the complete kanso app in which you are encountering this error, I can provide more guidance.

**Comment by nickperkinslondon** [comment]
Thanks! -- here it is:
https://github.com/nickperkinslondon/field-agent

( simplified from original -- but still has same problem )

**Comment by nickperkinslondon** [comment]
I have found that saving works if I add a @url attribute to my Model....but you said I didn't have to do that...

```
class Quote extends Spine.Model
    @configure "Quote","name"
    @extend Spine.Model.CouchAjax
    @url:'/field-agent'
```

**Comment by nickperkinslondon** [comment]
So I can save if I set the @url on my Model....but I still can't fetch() 
It tries to GET the exact same URL as it uses to POST when you save a doc.
In my case:

```
http://localhost:5984/field-agent
```

From reading the source it seems like it should be hitting a special view: "..by_modelname" or something?.
That view does exist on my ddoc, but it never gets hit.
It also looks, from the source, like my saved documents should have a "modelname" attribute magically added?
Is this true? ( they have no such attribute )
There is no mention of it in the docs, or of how couchdb URLs are used, or of the fact that you are adding a special "_view" to the system.  As a couchdb developer who is just starting to use Kanso and Spine for the first time, these are things that I want to know -- especially when things don't work right away.
I am also confused by the "duality" stuff -- it seems to be integral to the URL scheme, but I don't really understand it.  ( and my URLs don't seem to be working )

**Comment by nrw** [comment]
The first thing to do is add `spine-adapter`'s rewrites: https://github.com/nrw/kanso-spine-todos/blob/master/lib/rewrites.coffee#L7. If that doesn't solve your problem, I'll have time to give this another look later today.

**Comment by nrw** [comment]
The problem appears to be that you have built an app that does not utilize `_rewrites`, which are essential to `spine-adapter`. The root of your app should be accessible from `http://couchdb.location.com/database-name/_design/design-doc-name/_rewrite/`. I'd strongly encourage you to go clone the [example app](https://github.com/nrw/kanso-spine-todos) and use it as a starting point.

Bonus: It looks like you're manually compiling coffee-script (the `coffee-script-precompiler` package is used in the example app and does that automatically on every push).

Short answers to your other questions:
- yes, `modelname` is automatically added by `spine-adapter`
- no, you don't need to manually add any special `views` or `lists`
- there is a bit about `duality` [here](http://kan.so/docs/Duality) and an example app [here](https://github.com/caolan/blog)
